@startuml hard_skills

title "Cyber Security"

'left to right direction
'scale 1600 width

<style>
     title {
         FontSize 24
         FontColor black
     }
     legend {
         FontSize 24
         FontColor black
     }
     card {
         BackGroundColor #Yellow
         LineThickness 1
         LineColor black
     }
     rectangle {
         BackgroundColor none
         Padding-left 10
     }
</style>

skinparam linetype polyline
skinparam linetype ortho
skinparam componentStyle rectangle
skinparam rectangle {
    roundCorner 35
}

legend top center
    <color:Indigo><&task></color> - <b>Personal Recommendation</b> / Opinion
    <color:Green><&check></color> - <b>Alternative</b> Option - Pick this or purple
    <color:OrangeRed><&warning></color> - Order in roadmap <b>not strict</b> (<i>Learn anytime</i>)
    <color:Red><&ban></color> - I <b>wouldn't</b> recommend
    <color:LawnGreen><&media-stop></color> - (<i>highlight</i>) - I know it and <b>I use</b>
    <color:LightBlue><&media-stop></color> - (<i>highlight</i>) - I know this, but I <b>did not have the opportunity</b> to use it
end legend

component {
    card "<color:Indigo><&task></color> \
<b>CTFs (Capture the Flag)"                                                 as ctf  #text:Teal
    rectangle "<color:Green><&check></color> HackTheBox"                    as ctfh
    rectangle "<color:Green><&check></color> TryHackMe"                     as ctft
    rectangle "<color:Green><&check></color> VulnHub"                       as ctfv
    rectangle "<color:Green><&check></color> picoCTF"                       as ctfp
    rectangle "<color:Green><&check></color> SANS Holiday Hack Challenge"   as ctfs
}
ctf  .[hidden]d. ctfh
ctfh .[hidden]d. ctft
ctft .[hidden]d. ctfv
ctfv .[hidden]d. ctfp
ctfp .[hidden]d. ctfs

component {
    card "<color:Indigo><&task></color> \
<b>Certifications"                                                      as cert     #text:Teal

    rectangle "<color:Green><&check></color> Beginner Certifications"   as certbc {
        rectangle "<color:Green><&check></color> CompTIA A+"            as certta
        rectangle "<color:Green><&check></color> CompTIA Linux+"        as certtl
        rectangle "<color:Green><&check></color> CompTIA Network+"      as certtn
        rectangle "<color:Green><&check></color> CCNA"                  as certna
        rectangle "<color:Green><&check></color> CompTIA Security+"     as certts
    }
    rectangle "<color:Green><&check></color> Advanced Certifications"   as certac {
        rectangle "<color:Green><&check></color> CISSP"                 as certcs
        rectangle "<color:Green><&check></color> CISA"                  as certca
        rectangle "<color:Green><&check></color> CISM"                  as certcm
        rectangle "<color:Green><&check></color> GSEC"                  as certgs
        rectangle "<color:Green><&check></color> GPEN"                  as certgn
        rectangle "<color:Green><&check></color> GWAPT"                 as certgw
        rectangle "<color:Green><&check></color> GIAC"                  as certgi
        rectangle "<color:Green><&check></color> OSCP"                  as certos
        rectangle "<color:Green><&check></color> CREST"                 as certcr
        rectangle "<color:Green><&check></color> CEH"                   as certch
    }
}
certta .[hidden]r. certtl
certtn .[hidden]r. certna

certcs .[hidden]r. certca
certca .[hidden]r. certcm
certgs .[hidden]r. certgn
certgn .[hidden]r. certgw
certgi .[hidden]r. certos
certos .[hidden]r. certch

cert   .[hidden]d. certbc
certbc .[hidden]d. certta
certbc .[hidden]d. certtl
certta .[hidden]d. certtn
certtl .[hidden]d. certna
certtn .[hidden]d. certts
certna .[hidden]d. certts
certts .[hidden]d. certac
certac .[hidden]d. certcs
certac .[hidden]d. certca
certac .[hidden]d. certcm
certcs .[hidden]d. certgs
certca .[hidden]d. certgn
certcm .[hidden]d. certgw
certgs .[hidden]d. certgi
certgn .[hidden]d. certos
certgw .[hidden]d. certcr
certgi .[hidden]d. certch
certos .[hidden]d. certch
certcr .[hidden]d. certch

card "Cyber-security" as CS

start -[#blue;dashed;thickness=5]- CS

component {
    card "<color:Indigo><&task></color> \
<b>Fundamental IT Skills"                                                           as f  #text:Teal
'    rectangle "<color:Indigo><&check></color> Fundamental IT Skills"                as fits
    rectangle "<color:Green><&check></color> Computer Hardware Components"          as fchc
    rectangle "<color:Green><&check></color> Connection Types and their function"   as fctf

    rectangle "<color:Green><&check></color> OS-Independent Troubleshooting"        as fost
    rectangle "<color:Green><&check></color> Understand Basics of Popular Suites"   as fbps

    rectangle "<color:Green><&check></color> Basics of Computer Networking"         as fbcn
}

'rectangle "<color:Indigo><&check></color> Fundamental IT Skills"                as fits
'rectangle "<color:Green><&check></color> Computer Hardware Components"          as fchc
'rectangle "<color:Green><&check></color> Connection Types and their function"   as fctf
'
'rectangle "<color:Green><&check></color> OS-Independent Troubleshooting"        as fost
'rectangle "<color:Green><&check></color> Understand Basics of Popular Suites"   as fbps
'
'rectangle "<color:Green><&check></color> Basics of Computer Networking"         as fbcn

f    .[hidden]d. fchc
'fits .[hidden]d. fchc
fchc .[hidden]d. fctf
fctf .[hidden]d. fost
fost .[hidden]d. fbps
fbps .[hidden]d. fbcn

'f    .d. fchc
''fits .d. fchc
'fchc .d. fctf
'fctf .d. fost
'fost .d. fbps
'fbps .d. fbcn

rectangle "Types of connection"                                         as tc {
    rectangle "<color:Green><&check></color> NFC"                       as tcn
    rectangle "<color:Green><&check></color> WiFi"                      as tcw
    rectangle "<color:Green><&check></color> Bluetooth"                 as tcb
    rectangle "<color:Green><&check></color> Infrared"                  as tci
}
tcn .[hidden]r. tcw
tcw .[hidden]r. tcb
tcb .[hidden]r. tci

rectangle "Popular Suites"                                              as ps {
    rectangle "<color:Green><&check></color> iCloud"                    as psi
    rectangle "<color:Green><&check></color> Google Suite"              as psg
    rectangle "<color:Green><&check></color> Microsoft Office Suite"    as psm
}
psi .[hidden]r. psg
psg .[hidden]r. psm

fctf .l. tc
fbps .l. ps

CS -[#blue;thickness=3]- f

card "<color:Indigo><&task></color> <b>Operating Systems"                           as os  #text:Teal

rectangle "<color:Green><&check></color> Windows"                                   as winos
rectangle "<color:Green><&check></color> Linux"                                     as linux
rectangle "<color:Green><&check></color> MacOS"                                     as macos

rectangle "Learn following for Each"                                                as osl   {
    rectangle "<color:Green><&check></color> Installation and Configuration"        as oslic
    rectangle "<color:Green><&check></color> Different Versions and Differences"    as osldv
    rectangle "<color:Green><&check></color> Navigating using GUI and CLI"          as oslnv
    rectangle "<color:Green><&check></color> Understand Permissions"                as oslup
    rectangle "<color:Green><&check></color> Installing Software and Applications"  as oslsa
    rectangle "<color:Green><&check></color> Performing CRUD on Files"              as oslpf
    rectangle "<color:Green><&check></color> Troubleshooting"                       as oslts
    rectangle "<color:Green><&check></color> Common Commands"                       as oslcc
}
winos .[hidden]r. linux
linux .[hidden]r. macos

oslic .[hidden]. osldv
osldv .[hidden]. oslnv
oslnv .[hidden]. oslup
oslup .[hidden]. oslsa
oslsa .[hidden]. oslpf
oslpf .[hidden]. oslts
oslts .[hidden]. oslcc

os .u. winos
os .u. linux
os .u. macos
os .d. osl

f -[#blue;thickness=3]r- os

card "<color:Indigo><&task></color> Networking Knowledge"                           as net  #text:Teal

rectangle "Basic network knowledge"                                                 as netb    {
    rectangle "<color:Green><&check></color> Understand the OSI model"              as netbosi
    rectangle "<color:Green><&check></color> Common Protocols and their Uses"       as netbpro
    rectangle "<color:Green><&check></color> Common Ports and their Uses"           as netbprt
    rectangle "<color:Green><&check></color> SSL and TLS Basics"                    as netbssl
    rectangle "<color:Green><&check></color> Basics of NAS and SAN"                 as netbnas
}
netbosi .[hidden]. netbpro
netbpro .[hidden]. netbprt
netbprt .[hidden]. netbssl
netbssl .[hidden]. netbnas

net .d. netb

f -[#blue;thickness=3]r- net

component {
    card "<color:Indigo><&task></color> \
<b>Basics of Subnetting"                                                            as nets      #text:Teal
'rectangle "Basics of Subnetting"                                                    as nets    {
    rectangle "IT Terminology"                                                      as netsi   {
        rectangle "<color:Green><&check></color> Public vs Private IP Addresses"    as netsiad
        rectangle "<color:Green><&check></color> localhost"                         as netsilh
        rectangle "<color:Green><&check></color> loopback"                          as netsilb
        rectangle "<color:Green><&check></color> CIDR"                              as netsici
        rectangle "<color:Green><&check></color> subnet mask"                       as netsism
        rectangle "<color:Green><&check></color> default gateway"                   as netsidg
    }
    rectangle "Understand the Terminology"                                          as netso   {
        rectangle "<color:Green><&check></color> VLAN"                              as netsovl
        rectangle "<color:Green><&check></color> DMZ"                               as netsodm
        rectangle "<color:Green><&check></color> ARP"                               as netsoar
        rectangle "<color:Green><&check></color> VM"                                as netsovm
        rectangle "<color:Green><&check></color> NAT"                               as netsont
        rectangle "<color:Green><&check></color> IP"                                as netsoip
        rectangle "<color:Green><&check></color> DNS"                               as netsodn
        rectangle "<color:Green><&check></color> DHCP"                              as netsodh
        rectangle "<color:Green><&check></color> Router"                            as netsort
        rectangle "<color:Green><&check></color> Switch"                            as netsosw
        rectangle "<color:Green><&check></color> VPN"                               as netsovp
    }
    rectangle "Understand these"                                                    as netsk   {
        rectangle "<color:Green><&check></color> MAN"                               as netskma
        rectangle "<color:Green><&check></color> LAN"                               as netskla
        rectangle "<color:Green><&check></color> WAN"                               as netskwa
        rectangle "<color:Green><&check></color> WLAN"                              as netskwl
    }
    rectangle "Function of Each"                                                    as netsf   {
        rectangle "<color:Green><&check></color> DHCP"                              as netsfdh
        rectangle "<color:Green><&check></color> DNS"                               as netsfdn
        rectangle "<color:Green><&check></color> NTP"                               as netsfnt
        rectangle "<color:Green><&check></color> IPAM"                              as netsfip
    }
    rectangle "Network Topologies"                                                  as netst   {
        rectangle "<color:Green><&check></color> Star"                              as netstst
        rectangle "<color:Green><&check></color> Ring"                              as netstri
        rectangle "<color:Green><&check></color> Mesh"                              as netstme
        rectangle "<color:Green><&check></color> Bus"                               as netstbs
    }
    rectangle "Understand Common Protocols"                                         as netsp   {
        rectangle "<color:Green><&check></color> SSH"                               as netspss
        rectangle "<color:Green><&check></color> RDP"                               as netsprd
        rectangle "<color:Green><&check></color> FTP"                               as netspft
        rectangle "<color:Green><&check></color> SFTP"                              as netspsf
        rectangle "<color:Green><&check></color> HTTP / HTTPS"                      as netspht
        rectangle "<color:Green><&check></color> SSL / TLS"                         as netsptl
    }
}
' INTERNAL
netsilh .[hidden]r. netsilb
netsilb .[hidden]r. netsici
netsism .[hidden]r. netsidg
netsovl .[hidden]r. netsodm
netsodm .[hidden]r. netsoar
netsoar .[hidden]r. netsovm
netsont .[hidden]r. netsoip
netsoip .[hidden]r. netsodn
netsodn .[hidden]r. netsodh
netsort .[hidden]r. netsosw
netsosw .[hidden]r. netsovp
netskma .[hidden]r. netskla
netskla .[hidden]r. netskwa
netskwa .[hidden]r. netskwl
netsfdh .[hidden]r. netsfdn
netsfdn .[hidden]r. netsfnt
netsfnt .[hidden]r. netsfip
netstst .[hidden]r. netstri
netstri .[hidden]r. netstme
netstme .[hidden]r. netstbs
netspss .[hidden]r. netsprd
netsprd .[hidden]r. netspft
netspft .[hidden]r. netspsf
netspht .[hidden]r. netsptl
netsiad .[hidden]d. netsilh
netsiad .[hidden]d. netsici
netsilh .[hidden]d. netsism
netsici .[hidden]d. netsidg
netsovl .[hidden]d. netsont
netsovm .[hidden]d. netsodh
netsont .[hidden]d. netsort
netsodh .[hidden]d. netsovp
netspss .[hidden]d. netspht
netsprd .[hidden]d. netspht
netspft .[hidden]d. netsptl
netspsf .[hidden]d. netsptl
' CARD POSITION
netsosw .[hidden]d. nets
nets    .[hidden]d. netskla
nets    .[hidden]d. netskwa
' EXTERNAL
netsism .[hidden]d. netsovl
netsidg .[hidden]d. netsovm
netsort .[hidden]d. netskma
netsovp .[hidden]d. netskwl
netskma .[hidden]d. netsfdh
netskwl .[hidden]d. netsfip
netsfdh .[hidden]d. netstst
netsfip .[hidden]d. netstbs
netstst .[hidden]d. netspss
netstbs .[hidden]d. netspsf

net .l. nets

rectangle "Deep knowledge"                                                          as netd    {
    rectangle "Common Virtualization Technologies"                                  as netdc   {
        rectangle "<color:Green><&check></color> VMWare"                            as netdcwr
        rectangle "<color:Green><&check></color> VirtualBox"                        as netdcvb
        rectangle "<color:Green><&check></color> esxi"                              as netdcex
        rectangle "<color:Green><&check></color> proxmox"                           as netdcpm
    }
    rectangle "<color:Green><&check></color> Understand basics of Virtualization"   as netdv   {
        rectangle "<color:Green><&check></color> Hypervisor"                        as netdvhv
        rectangle "<color:Green><&check></color> VM"                                as netdvvm
        rectangle "<color:Green><&check></color> GuestOS"                           as netdvgo
        rectangle "<color:Green><&check></color> HostOS"                            as netdvho
    }
    rectangle "<color:Green><&check></color> Troubleshooting Tools"                 as netdt   {
        rectangle "<color:Green><&check></color> nslookup"                          as netdtns
        rectangle "<color:Green><&check></color> iptables"                          as netdtit
        rectangle "<color:Green><&check></color> Packet Sniffers"                   as netdtps
        rectangle "<color:Green><&check></color> ipconfig"                          as netdtic
        rectangle "<color:Green><&check></color> netstat"                           as netdtst
        rectangle "<color:Green><&check></color> Port Scanners"                     as netdtsc
        rectangle "<color:Green><&check></color> ping"                              as netdtpi
        rectangle "<color:Green><&check></color> dig"                               as netdtdi
        rectangle "<color:Green><&check></color> arp"                               as netdtar
        rectangle "<color:Green><&check></color> Protocol Analyzers"                as netdtpa
        rectangle "<color:Green><&check></color> nmap"                              as netdtnm
        rectangle "<color:Green><&check></color> route"                             as netdtro
        rectangle "<color:Green><&check></color> tcpdump"                           as netdttc
        rectangle "<color:Green><&check></color> tracert"                           as netdttr
    }
    rectangle "<color:Green><&check></color> Authentication Methodologies"          as netda   {
        rectangle "<color:Green><&check></color> Kerberos"                          as netdakr
        rectangle "<color:Green><&check></color> LDAP"                              as netdald
        rectangle "<color:Green><&check></color> SSO"                               as netdass
        rectangle "<color:Green><&check></color> Certificates"                      as netdace
        rectangle "<color:Green><&check></color> Local Auth"                        as netdala
        rectangle "<color:Green><&check></color> RADIUS"                            as netdara
    }
}
' INTERNAL
netdcwr .[hidden]r. netdcvb
netdcvb .[hidden]r. netdcex
netdcex .[hidden]r. netdcpm
netdvhv .[hidden]r. netdvvm
netdvvm .[hidden]r. netdvgo
netdvgo .[hidden]r. netdvho
netdtns .[hidden]r. netdtit
netdtit .[hidden]r. netdtps
netdtic .[hidden]r. netdtst
netdtst .[hidden]r. netdtsc
netdtpi .[hidden]r. netdtdi
netdtdi .[hidden]r. netdtar
netdtar .[hidden]r. netdtpa
netdtnm .[hidden]r. netdtro
netdtro .[hidden]r. netdttc
netdttc .[hidden]r. netdttr
netdakr .[hidden]r. netdald
netdald .[hidden]r. netdass
netdace .[hidden]r. netdala
netdala .[hidden]r. netdara
netdtns .[hidden]d. netdtic
netdtic .[hidden]d. netdtpi
netdtpi .[hidden]d. netdtnm
netdtps .[hidden]d. netdtsc
netdtsc .[hidden]d. netdtpa
netdtpa .[hidden]d. netdttr
netdakr .[hidden]d. netdace
netdass .[hidden]d. netdara
' EXTERNAL
netdcwr .[hidden]d. netdvhv
netdvhv .[hidden]d. netdtns
netdtnm .[hidden]d. netdakr
netdcpm .[hidden]d. netdvho
netdvho .[hidden]d. netdtps
netdttr .[hidden]d. netdass

nets .l. netd

component {
    card "<color:Indigo><&task></color> \
<b>Security Skills and Knowledge"                           as lrn  #text:Teal
}

component {
    card "<color:Indigo><&task></color> \
<b>"                                            as lrn  #text:Teal
'Understand Common Hacking Tools
'Understand Common Exploit Frameworks
'Understand Concept of Defense in Depth
'Understand Concept of Runbooks
'Understand Basics of Forensics
'Basics and Concepts of Threat Hunting
'Basics of Vulnerability Management
'Basics of Reverse Engineering
'Penetration Testing Rules of Engagement
'Perimiter vs DMZ vs Segmentation
}

component {
    card "<color:Indigo><&task></color> \
<b>"                           as lrn  #text:Teal
'Core Concepts of Zero Trust
'Roles of Compliance and Auditors
'Understand the Definition of Risk
'Understand Backups and Resiliency
'Cyber Kill Chain MFA and 2FA
'Operating System Hardening
'Understand the Concept of Isolation
'Basics of IDS and IPS Honeypots
'Authentication vs Authorization
}

component {
    card "<color:Indigo><&task></color> \
<b>"                           as lrn  #text:Teal
'Blue Team vs Red Team vs Purple Team
'False Negative / False Positive True Negative / True Positive
'Basics of Threat Intel, OSINT
'Understand Handshakes
'Understand CIA Triad
'Privilege escalation / User based Attacks
'Web Based Attacks and OWASP 10
'Learn how Malware Operates and Types
}

component {
    component {
        card "<color:Indigo><&task></color> \
    <b>Tools for Incident Response and Discovery"   as lrn  #text:Teal
    'nmap tracert nslookup dig curl
    'ipconfig hping ping arp cat dd
    'head tail grep wireshark winhex
    'memdump FTK Imager autopsy
    }
    component {
        card "<color:Indigo><&task></color> \
    <b>Understand Frameworks"                       as lrn  #text:Teal
    'ATT&CK Kill chain Diamond Model
    }
    component {
        card "<color:Indigo><&task></color> \
    <b>Understand Common Standards"                 as lrn  #text:Teal
    'ISO NIST RMF CIS CSF
    }
    component {
        card "<color:Indigo><&task></color> \
    <b>Understand"                                  as lrn  #text:Teal
    'SIEM SOAR
    }
    component {
        card "<color:Indigo><&task></color> \
    <b>Common Distros for Hacking"                  as lrn  #text:Teal
    'ParrotOS Kali Linux
    }
    component {
        card "<color:Indigo><&task></color> \
    <b>Using tools for unintended purposes"         as lrn  #text:Teal
    'LOLBAS
    }
    component {
        card "<color:Indigo><&task></color> \
    <b>Learn how to find and use these logs"        as lrn  #text:Teal
    'Event Logs syslogs netflow
    'Packet Captures Firewall Logs
    }
    component {
        card "<color:Indigo><&task></color> \
    <b>Understand Hardening Concepts"               as lrn  #text:Teal
    'MAC-based NAC-based Port Blocking
    'Group Policy ACLs Sinkholes Patching
    'Jump Server Endpoint Security
    }
}

component {
    component {
        card "<color:Indigo><&task></color> \
    <b>Basics of Cryptography"                                      as lrn  #text:Teal
    'Salting Hashing Key Exchange
    'PKI Pvt Key vs Pub Key Obfuscation
    }
    component {
        card "<color:Indigo><&task></color> \
    <b>Understand Secure vs Unsecure Protocols"                     as lrn  #text:Teal
    'FTP vs SFTP SSL vs TLS IPSEC
    'DNSSEC LDAPS SRTP S/MIME
    }
    component {
        card "<color:Indigo><&task></color> \
    <b>Understand the following Terms"                              as lrn  #text:Teal
    'Antivirus Antimalware EDR DLP
    'Firewall and Nextgen Firewall HIPS
    'NIDS NIPS Host Based Firewall
    'Sandboxing ACL EAP vs PEAP
    'WPA vs WPA2 vs WPA3 vs WEP WPS
    }
    component {
        card "<color:Indigo><&task></color> \
    <b>Understand the Incident Response Process"                    as lrn  #text:Teal
    'Preparation Identification
    'Containment Eradication
    'Recovery Lessons Learned
    }
    component {
        card "<color:Indigo><&task></color> \
    <b>Understand Threat Classification"                            as lrn  #text:Teal
    'Zero Day Known vs Unknown APT
        rectangle "<color:Green><&check></color> Zero Day"          as lrnp
        rectangle "<color:Indigo><&task></color> Known vs Unknown"  as lrng
        rectangle "<color:Green><&check></color> APT"               as lrnt
    }
    component {
        card "<color:Indigo><&task></color> \
    <b>Understand Common Tools"                     as lrn  #text:Teal
    'VirusTotal Joe Sandbox any.run urlvoid urlscan WHOIS
    }
}

component {
    component {
        card "<color:Indigo><&task></color> \
    <b>Attack Types and Differences"                     as lrn  #text:Teal
    'Phishing vs Vishing vs Whaling vs Smishing
    'Spam vs Spim Shoulder Surfing
    'Dumpster Diving Tailgating Zero Day
    'Social Engineering Reconnaissance
    'Impersonation Watering Hole Attack
    'Drive by Attack Typo Squatting
    'Brute Force vs Password Spray
    }
    component {
        card "<color:Indigo><&task></color> \
    <b>Common Network Based Attacks"                        as lrn  #text:Teal
    'DoS vs DDoS MITM ARP Poisoning
    'Evil Twin DNS Poisoning Spoofing
    'Deauth Attack VLAN Hopping
    'Rogue Access Point War-driving/dialing
    }
    component {
        card "<color:Indigo><&task></color> \
    <b>"                                                    as lrn  #text:Teal
    'Buffer Overflow Memory Leak XSS
    'SQL Injection CSRF Replay Attack
    'Pass the Hash Directory Traversal
    }
    component {
        card "<color:Indigo><&task></color> \
    <b>Understand Audience"                                 as lrn  #text:Teal
    'Stakeholders HR Legal Compliance
    'Management
    }
}

component {
    card "<color:Indigo><&task></color> \
<b>Cloud skills and Knowledge"                           as lrn  #text:Teal
}

component {
    card "<color:Indigo><&task></color> \
<b>"                           as lrn  #text:Teal
'Understand concepts of security in the cloud
'Understand the basics and general flow of deploying in the cloud
'Understand the di"erences between cloud and on-premises
'Understand the concept of infrastructure as code
'Understand the concept of Serverless
'Understand the concept of CDN
}

component {
    card "<color:Indigo><&task></color> \
<b>Understand Cloud Services"                           as lrn  #text:Teal
'SaaS PaaS IaaS
}
component {
    card "<color:Indigo><&task></color> \
<b>Common Cloud Environments"                           as lrn  #text:Teal
'AWS GCP Azure
}

component {
    card "<color:Indigo><&task></color> \
<b>Cloud Models"                           as lrn  #text:Teal
'Private Public Hybrid
}
component {
    card "<color:Indigo><&task></color> \
<b>Common Cloud Storage"                           as lrn  #text:Teal
'S3 Dropbox Box
'OneDrive Google Drive
'iCloud
}

component {
    card "<color:Indigo><&task></color> \
<b>Programming Skills and Knowledge (Optional But Recommended)"       as lrn  #text:Teal
}

'Python
'Go
'JavaScript
'C++
'Bash
'PowerShell

'Keep Learning

@enduml